name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t arunima1/wisecow:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username arunima1 --password-stdin

      - name: Push Docker image
        run: |
          docker push arunima1/wisecow-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl set image deployment/wisecow-deployment wisecow=arunima1/wisecow-app:${{ github.sha }} --record
